"""Demo 3 — label-provenance gate on REAL data (Breast Cancer Wisconsin, bundled, offline).

No leakage here — a clean random split. The point is the SECOND gate: some evaluation labels were
"imputed by a model" (silver labels) instead of human-attested. Scoring against model-generated gold
means measuring a model partly against another model's guesses. Lineage CleanRoom flags it.

Run:  python -m demos.demo_provenance_gate
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from sklearn.datasets import load_breast_cancer

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from lineage_cleanroom import SplitView, audit_split, make_console_sink, write_report
from demos._common import OUT


def main():
    d = load_breast_cancer()
    X, y, names = d.data, d.target.astype(int), list(d.feature_names)
    rng = np.random.default_rng(0)
    p = rng.permutation(len(y))
    cut = int(0.7 * len(y))
    tr, te = p[:cut], p[cut:]

    # 30% of the EVALUATION labels were generated by a model (not human-attested).
    prov_test = np.array(["human"] * len(te), dtype=object)
    silver = rng.choice(len(te), size=int(0.3 * len(te)), replace=False)
    prov_test[silver] = "model:imputed"

    view = SplitView(
        X_train=X[tr], y_train=y[tr], X_test=X[te], y_test=y[te], feature_names=names,
        prov_train=np.array(["human"] * len(tr), dtype=object), prov_test=prov_test)
    res = audit_split(view, emit=make_console_sink())

    paths = write_report(res, OUT, stem="breast_cancer_provenance")
    (OUT / "breast_cancer_provenance.summary.txt").write_text(
        f"Dataset: Breast Cancer Wisconsin (scikit-learn bundled, real) — provenance gate demo\n"
        f"leakage gate (features)  : {'leaked' if res.leak_report['leaked'] else 'clean'}\n"
        f"provenance gate (labels) : {'VIOLATION' if not res.passed else 'clean'}\n"
        f"human fraction in eval   : {res.provenance_report.get('human_fraction_test')}\n"
        f"verdict                  : {res.verdict}\n", encoding="utf-8")

    print(f"\nDEMO provenance: leakage={'yes' if res.leak_report['leaked'] else 'no'}, "
          f"passed={res.passed}")
    print(f"verdict: {res.verdict}")
    return {"result": res}


if __name__ == "__main__":
    main()
